name: hmd-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - polars>=0.20
  - pandas>=2.0
  - numpy>=1.24
  - pyarrow>=14.0
  - matplotlib>=3.7
  - pandera>=0.18
  - jupyter
  - jupyterlab
  # Testing
  - pytest>=7.4
  - pytest-cov>=4.1
  - pip
  - pip:
    - aquarel
    - orjson
